# Используем официальный образ .NET SDK
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем проект и восстанавливаем зависимости
COPY *.csproj ./
RUN dotnet restore

# Копируем оставшиеся файлы и строим проект
COPY . ./
RUN dotnet publish -c Release -o out

# Используем официальный образ для работы с приложением
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Копируем собранный артефакт
COPY --from=build /app/out .

# Запуск приложения
ENTRYPOINT ["dotnet", "TaskManager.dll"]